import Header from '@/components/app/Header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="flex min-h-screen flex-col justify-between">
          {children}
        </main>
      </body>
      {/* learn more at https://garchi.co.uk/documentation/1.0/headlessweb/next-app-router */}
      <Script src="https://garchi.co.uk/script/index.es.js" />
    </html>
  )
}
